emotions:
  happy:
    name: happy
    exaggeration: 0.3
    voice_samples:
    - /home/ross/workspace/chatterbox-streaming/configs/voice_samples/happy/Chessboard_Limbo_CommonAvatar_Nicole_016.wav
    created_at: '2025-08-08T21:24:03.656074'
    updated_at: '2025-08-09T08:21:24.940410'
  sad:
    name: sad
    exaggeration: 0.3
    voice_samples:
    - audio_data/Comic_Chapter0_Nicole_019.wav
    - audio_data/Comic_Chapter0_Nicole_026.wav
    created_at: '2025-08-08T21:24:03.656105'
    updated_at: '2025-08-08T21:24:03.656105'
  neutral:
    name: neutral
    exaggeration: 0.5
    voice_samples:
    - /home/ross/workspace/chatterbox-streaming/configs/voice_samples/neutral/Chessboard_Limbo_CommonAvatar_Nicole_003.wav
    created_at: '2025-08-08T21:24:03.656109'
    updated_at: '2025-08-09T08:15:35.704799'
  excited:
    name: excited
    exaggeration: 0.85
    voice_samples:
    - audio_data/GalGame_Chapter050_Nicole_010_001.wav
    - audio_data/GalGame_Chapter050_Nicole_010_003.wav
    - audio_data/Accompany_Nicole_Event04_05.wav
    created_at: '2025-08-08T21:24:03.656112'
    updated_at: '2025-08-08T21:24:03.656112'
  angry:
    name: angry
    exaggeration: 0.5
    voice_samples:
    - /home/ross/workspace/chatterbox-streaming/configs/voice_samples/angry/Chessboard_Limbo_CommonAvatar_Nicole_015.wav
    created_at: '2025-08-08T21:24:03.656115'
    updated_at: '2025-08-09T08:20:25.108593'
  afraid:
    name: afraid
    exaggeration: 0.5
    voice_samples: []
    created_at: '2025-08-09T07:59:10.595105'
    updated_at: '2025-08-09T08:17:04.572213'
  smug:
    name: smug
    exaggeration: 0.5
    voice_samples:
    - /home/ross/workspace/chatterbox-streaming/configs/voice_samples/smug/Comic_Chapter0_Nicole_007.wav
    created_at: '2025-08-09T07:59:36.416868'
    updated_at: '2025-08-09T08:22:21.043190'
  embarrassed:
    name: embarrassed
    exaggeration: 0.5
    voice_samples: []
    created_at: '2025-08-09T07:59:47.151178'
    updated_at: '2025-08-09T07:59:47.151178'
  confused:
    name: confused
    exaggeration: 0.5
    voice_samples: []
    created_at: '2025-08-09T08:00:29.389591'
    updated_at: '2025-08-09T08:00:29.389591'
  flirty:
    name: flirty
    exaggeration: 0.3
    voice_samples:
    - /home/ross/workspace/chatterbox-streaming/configs/voice_samples/flirty/Chessboard_Limbo_CommonAvatar_Nicole_006.wav
    created_at: '2025-08-09T08:00:39.887822'
    updated_at: '2025-08-09T08:18:41.546266'
